function installSimscapePayloadGeometry(projectRoot)
% installSimscapePayloadGeometry - 统一刚性载荷实体的横卧圆柱几何与惯量坐标
arguments
    projectRoot {mustBeTextScalar} = ""
end

if strlength(string(projectRoot)) == 0
    projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
end
projectRoot = char(projectRoot);
modelFile = fullfile(projectRoot, 'matlab', 'stewart_platform_model.slx');
load_system(modelFile);
cleanup = onCleanup(@() close_system('stewart_platform_model', 0));

solid = 'stewart_platform_model/Payload/Rigid/Cylindrical Solid';
transform = 'stewart_platform_model/Payload/Rigid/Rigid Transform';
set_param(solid, ...
    'CylinderRadius', 'payload.radius', ...
    'CylinderLength', 'payload.length', ...
    'CenterOfMass', '[0 0 0]', ...
    'MomentsOfInertia', 'diag(payload.I_local)', ...
    'ProductsOfInertia', ...
        '[payload.I_local(2,3) payload.I_local(1,3) payload.I_local(1,2)]');
set_param(transform, ...
    'TranslationMethod', 'Cartesian', ...
    'TranslationCartesianOffset', 'payload.center', ...
    'RotationMethod', 'RotationMatrix', ...
    'RotationMatrix', 'payload.R');

save_system('stewart_platform_model', modelFile);
clear cleanup;
end
