function result = run_14_strict_clf_cbf_qp_exact_model_study( ...
        trajectoryFile, outputDir, options)
% run_14_strict_clf_cbf_qp_exact_model_study - Exact-model ablation and robustness study.
%
% The study compares computed-torque + LQI, CLF-QP, and the complete
% strict CLF-CBF-QP from one common initial state.  It then applies the
% complete controller to matched dynamics, +20 percent moving-body mass,
% a prescribed centre-of-mass offset, and a 30 ms first-order actuator.
% The controller always uses the nominal model.  Consequently, the strict
% invariance claim is marked applicable only to the matched, ideal-force
% complete-QP case.
arguments
    trajectoryFile {mustBeTextScalar} = ""
    outputDir {mustBeTextScalar} = ""
    options struct = struct()
end

runRoot = fileparts(mfilename('fullpath'));
controllerRoot = fileparts(runRoot);
projectRoot = fileparts(controllerRoot);
addpath(fullfile(projectRoot, 'src'));
addpath(fullfile(projectRoot, 'matlab'));
addpath(fullfile(projectRoot, 'opt_minimal', 'core'));
addpath(fullfile(controllerRoot, 'simscape_tracking'));
addpath(fullfile(controllerRoot, 'strict_clf_cbf_qp'));
addpath(fullfile(controllerRoot, 'exact_model_study'));

settings = defaultSettings();
settings = mergeKnownFields(settings, options);
validateSettings(settings);
if strlength(string(outputDir)) == 0
    outputDir = fullfile(projectRoot, 'results', 'reports', ...
        'strict_clf_cbf_qp', 'exact_model_study');
end
outputDir = char(outputDir);
if ~exist(outputDir, 'dir')
    mkdir(outputDir);
end

% Reuse the established midterm computed-torque/LQI preparation path,
% including its established nonideal-actuator linearization.  The Simscape
% model is used only to recover that LQI design; every study trajectory
% below is generated by explicit nonlinear numerical integration of
% stateDynamicsCompositeRigidBody.
baselineOverrides = settings.baselineOverrides;
setup = prepareSimscapePoseForceControl(trajectoryFile, baselineOverrides);
modelCleanup = onCleanup(@() closePreparedModel(setup.modelName));

reference = makeReference(setup.refs, settings.stopTime);
dt = median(diff(reference.time));
if max(abs(diff(reference.time)-dt)) > 1e-11
    error('run_14_strict_clf_cbf_qp_exact_model_study:NonuniformReference', ...
        'The exact-model study requires a uniform control grid.');
end

discreteLqi = c2d(setup.design.K, dt, 'tustin');
strictOverrides = settings.strictOverrides;
strictOverrides.dt = dt;
strictConfig = makeStrictClfCbfQpConfig(setup.model, strictOverrides);
if strictConfig.cbf.collisionAlpha1 ~= 12 || ...
        strictConfig.cbf.collisionAlpha2 ~= 12
    warning('run_14_strict_clf_cbf_qp_exact_model_study:CollisionGainChanged', ...
        ['The publication default is alpha_1=alpha_2=12.  This run uses ' ...
         'alpha_1=%.6g and alpha_2=%.6g by explicit override.'], ...
        strictConfig.cbf.collisionAlpha1, strictConfig.cbf.collisionAlpha2);
end

scenarios = buildScenarios(setup.model, settings);
runsCell = cell(numel(scenarios), 1);
for scenarioIndex = 1:numel(scenarios)
    scenario = scenarios(scenarioIndex);
    fprintf('\n===== Exact nonlinear study: %s =====\n', scenario.displayName);
    runsCell{scenarioIndex} = simulateStrictExactModelScenario( ...
        reference, setup.model, setup.scene, setup.config, discreteLqi, ...
        strictConfig, scenario, settings);
    printRunMetrics(runsCell{scenarioIndex});
end
runs = vertcat(runsCell{:});

summary = summarizeStrictExactModelStudy(runs);
activeConstraintSummary = summarizeStrictActiveConstraints(runs);

result = struct();
result.method = "Exact nonlinear computed-torque/LQI and strict CLF-CBF-QP study";
result.generatedAt = datetime('now', 'TimeZone', 'Asia/Shanghai');
result.trajectoryFile = string(setup.trajectoryFile);
result.outputDir = string(outputDir);
result.reference = reference;
result.nominalModel = setup.model;
result.scene = setup.scene;
result.poseControllerConfig = setup.config;
result.strictConfig = strictConfig;
result.initialState = [reference.q(:, 1)+settings.initialPoseOffset; ...
    reference.qd(:, 1)+settings.initialVelocityOffset];
result.settings = settings;
result.runs = runs;
result.ablationIndices = [1, 2, 3];
result.robustnessIndices = [3, 4, 5, 6];
result.summary = summary;
result.activeConstraintSummary = activeConstraintSummary;
result.guaranteeStatement = [ ...
    "The forward-invariance claim is attached only to full_qp_nominal: " ...
    "nominal controller model, matched nominal plant, and ideal force input. " ...
    "Perturbed-model and actuator-lag runs are engineering robustness tests."];

artifactPaths = struct();
if settings.writeArtifacts
    artifactPaths.summaryCsv = string(fullfile(outputDir, ...
        'exact_model_study_summary.csv'));
    artifactPaths.activeConstraintCsv = string(fullfile(outputDir, ...
        'exact_model_study_active_constraints.csv'));
    writetable(summary, artifactPaths.summaryCsv);
    writetable(activeConstraintSummary, artifactPaths.activeConstraintCsv);
    writeStrictExactModelStudySummary(fullfile(outputDir, ...
        'exact_model_study_readme.txt'), result);
end
if settings.exportFigures
    artifactPaths.figures = exportStrictExactModelStudy( ...
        runs, strictConfig, outputDir, settings.figureResolution);
end
result.artifactPaths = artifactPaths;

if settings.writeArtifacts
    matFile = fullfile(outputDir, ...
        'strict_clf_cbf_qp_exact_model_study.mat');
    result.artifactPaths.matFile = string(matFile);
    save(matFile, 'result', '-v7.3');
end

matchedRun = runs(3);
if settings.failOnMatchedViolation && ~matchedRun.metrics.strictMatchedPassed
    error('run_14_strict_clf_cbf_qp_exact_model_study:MatchedAcceptanceFailed', ...
        ['The matched ideal-force strict-QP run did not satisfy every ' ...
         'declared numerical acceptance item.  Results were preserved.']);
end
clear modelCleanup;
end

function settings = defaultSettings()
settings = struct();
settings.stopTime = [];
settings.integrationSubsteps = 2;
settings.initialPoseOffset = [0.0004; -0.0003; 0.0002; ...
    0.0002; -0.00015; 0.0001];
settings.initialVelocityOffset = zeros(6, 1);
settings.massScale = 1.20;
settings.comOffset = [10; -8; 5] * 1e-3;
settings.actuatorLag = 0.030;
settings.strictOverrides = struct();
settings.baselineOverrides = struct();
settings.writeArtifacts = true;
settings.exportFigures = true;
settings.figureResolution = 220;
settings.failOnMatchedViolation = false;
settings.hardConstraintTolerance = 1e-7;
settings.stateConstraintTolerance = 2e-6;
settings.trackingTranslationPeakLimit = 3e-2;
settings.trackingRotationPeakLimit = deg2rad(1);
end

function target = mergeKnownFields(target, source)
fields = fieldnames(source);
for index = 1:numel(fields)
    name = fields{index};
    if ~isfield(target, name)
        error('run_14_strict_clf_cbf_qp_exact_model_study:UnknownOption', ...
            'Unknown exact-model study option: %s.', name);
    end
    target.(name) = source.(name);
end
end

function validateSettings(settings)
if ~isempty(settings.stopTime)
    validateattributes(settings.stopTime, {'double'}, ...
        {'scalar', 'positive', 'finite'});
end
validateattributes(settings.integrationSubsteps, {'double'}, ...
    {'scalar', 'integer', 'positive', 'finite'});
validateattributes(settings.initialPoseOffset, {'double'}, ...
    {'real', 'finite', 'size', [6, 1]});
validateattributes(settings.initialVelocityOffset, {'double'}, ...
    {'real', 'finite', 'size', [6, 1]});
validateattributes(settings.massScale, {'double'}, ...
    {'scalar', 'finite', '>', 1});
validateattributes(settings.comOffset, {'double'}, ...
    {'real', 'finite', 'size', [3, 1]});
validateattributes(settings.actuatorLag, {'double'}, ...
    {'scalar', 'positive', 'finite'});
validateattributes(settings.figureResolution, {'double'}, ...
    {'scalar', 'integer', 'positive'});
validateattributes(settings.hardConstraintTolerance, {'double'}, ...
    {'scalar', 'positive', 'finite'});
validateattributes(settings.stateConstraintTolerance, {'double'}, ...
    {'scalar', 'positive', 'finite'});
validateattributes(settings.trackingTranslationPeakLimit, {'double'}, ...
    {'scalar', 'positive', 'finite'});
validateattributes(settings.trackingRotationPeakLimit, {'double'}, ...
    {'scalar', 'positive', 'finite'});
end

function reference = makeReference(refs, stopTime)
lastIndex = numel(refs.t);
if ~isempty(stopTime)
    candidates = find(refs.t <= stopTime+1e-12);
    if numel(candidates) < 2
        error('run_14_strict_clf_cbf_qp_exact_model_study:StopTimeTooShort', ...
            'stopTime must retain at least two control samples.');
    end
    lastIndex = candidates(end);
end
indices = 1:lastIndex;
reference = struct();
reference.time = refs.t(indices);
reference.q = refs.q(:, indices);
reference.qd = refs.qd(:, indices);
reference.qdd = refs.qdd(:, indices);
reference.computedForce = refs.Fcomputed(:, indices);
reference.legLength = refs.L(:, indices);
reference.legSpeed = refs.Ld(:, indices);
reference.interpolation = string(refs.referenceInterpolation);
end

function scenarios = buildScenarios(nominalModel, settings)
massPlant = nominalModel;
massPlant.dynamics.totalMass = settings.massScale * ...
    nominalModel.dynamics.totalMass;
% Scale the inertia consistently while holding the centre of mass fixed so
% the mass test does not duplicate the separate COM-offset experiment.
massPlant.dynamics.inertiaAtCOM_P = settings.massScale * ...
    nominalModel.dynamics.inertiaAtCOM_P;
platformMass = nominalModel.dynamics.totalMass - ...
    nominalModel.dynamics.objectMass;
massPlant.dynamics.objectMass = massPlant.dynamics.totalMass-platformMass;

comPlant = nominalModel;
comPlant.dynamics.comP = nominalModel.dynamics.comP + settings.comOffset;

template = struct('id', "", 'displayName', "", 'studyGroup', "", ...
    'controllerMode', "", 'disturbance', "", 'plantModel', nominalModel, ...
    'actuatorLag', 0, 'guaranteeApplicable', false);
scenarios = repmat(template, 6, 1);
scenarios(1) = makeScenario(template, "ct_lqi", ...
    "Computed torque + LQI", "ablation", "baseline", ...
    "none", nominalModel, 0, false);
scenarios(2) = makeScenario(template, "clf_qp", ...
    "CLF-QP (force/rate bounds)", "ablation", "clf-only", ...
    "none", nominalModel, 0, false);
scenarios(3) = makeScenario(template, "full_qp_nominal", ...
    "Strict CLF-CBF-QP, nominal", "ablation+robustness", "full", ...
    "matched nominal plant, ideal force", nominalModel, 0, true);
scenarios(4) = makeScenario(template, "full_qp_mass_120", ...
    "Strict QP, mass +20%", "robustness", "full", ...
    "moving-body mass and inertia +20%, COM fixed", massPlant, 0, false);
scenarios(5) = makeScenario(template, "full_qp_com_offset", ...
    "Strict QP, COM offset", "robustness", "full", ...
    sprintf('COM offset [%g, %g, %g] mm', settings.comOffset*1e3), ...
    comPlant, 0, false);
scenarios(6) = makeScenario(template, "full_qp_lag_30ms", ...
    "Strict QP, actuator lag 30 ms", "robustness", "full", ...
    "first-order force actuator, tau=30 ms", nominalModel, ...
    settings.actuatorLag, false);
end

function value = makeScenario(template, id, displayName, group, mode, ...
        disturbance, plantModel, actuatorLag, guaranteeApplicable)
value = template;
value.id = string(id);
value.displayName = string(displayName);
value.studyGroup = string(group);
value.controllerMode = string(mode);
value.disturbance = string(disturbance);
value.plantModel = plantModel;
value.actuatorLag = actuatorLag;
value.guaranteeApplicable = guaranteeApplicable;
end

function printRunMetrics(run)
m = run.metrics;
fprintf(['position RMSE=%.6g m, rotation RMSE=%.6g rad, ' ...
    'max |Ldd|=%.6g m/s^2\n'], ...
    m.translationRmse, m.rotationRmse, m.maxLegAcceleration);
fprintf(['min collision margin=%.6g m, min sigma=%.6g, ' ...
    'fallback=%d, infeasible=%d\n'], ...
    m.minActualCollisionMargin, m.minSigma, ...
    m.fallbackCount, m.infeasibleCount);
if m.terminatedEarly
    fprintf('terminated early at t=%.6g s: %s\n', ...
        run.termination.time, run.termination.reason);
end
if isfinite(m.qpTimeP95)
    fprintf(['QP mean/p95/max = %.6g / %.6g / %.6g s, ' ...
        'strict matched pass=%d\n'], ...
        m.qpTimeMean, m.qpTimeP95, m.qpTimeMax, ...
        m.strictMatchedPassed);
end
end

function closePreparedModel(modelName)
if bdIsLoaded(modelName)
    set_param(modelName, 'Dirty', 'off');
    close_system(modelName, 0);
end
end
