function summary = summarizeDisturbanceRuns(runs, validationStage)
% summarizeDisturbanceRuns - Flatten exact/Simscape run evidence to one CSV row.
arguments
    runs struct
    validationStage {mustBeTextScalar} = "exact"
end

count = numel(runs);
controller = strings(count, 1);
caseId = strings(count, 1);
disturbance = strings(count, 1);
stage = repmat(string(validationStage), count, 1);
scale = zeros(count, 1);
seed = nan(count, 1);
values = nan(count, 43);
for index = 1:count
    controller(index) = runs(index).controller.id;
    caseId(index) = runs(index).experimentCase.id;
    disturbance(index) = runs(index).experimentCase.disturbanceType;
    scale(index) = runs(index).experimentCase.scale;
    seed(index) = runs(index).experimentCase.noiseSeed;
    m = runs(index).metrics;
    values(index, :) = [m.equivalentPoseRms, m.equivalentPosePeak, ...
        m.recoveryTime, m.translationRms, m.translationPeak, ...
        m.rotationRms, m.rotationPeak, m.minLegLength, m.maxLegLength, ...
        m.maxLegSpeed, m.maxLegAcceleration, m.peakForce, ...
        m.peakForceRate, m.controlEnergy, m.controllerTimeP95, ...
        m.qpTimeP95, m.dobTimeP95, m.infeasibleCount, m.fallbackCount, ...
        m.minSigma, m.minCollisionMargin, m.minCbfResidual, ...
        m.lengthViolationCount, m.speedViolationCount, ...
        m.accelerationViolationCount, m.forceViolationCount, ...
        m.forceRateViolationCount, ...
        m.collisionViolationCount, m.singularityViolationCount, ...
        m.nonfiniteCount, m.fullTrajectoryCompleted, ...
        m.hardConstraintsPassed, m.eligible, ...
        runs(index).experimentCase.isTraining, runs(index).experimentCase.isHoldout];
end
names = {'equivalent_pose_rms', 'equivalent_pose_peak', 'recovery_time_s', ...
    'translation_rms_x', 'translation_rms_y', 'translation_rms_z', ...
    'translation_peak_x', 'translation_peak_y', 'translation_peak_z', ...
    'rotation_rms_roll', 'rotation_rms_pitch', 'rotation_rms_yaw', ...
    'rotation_peak_roll', 'rotation_peak_pitch', 'rotation_peak_yaw', ...
    'min_leg_length_m', 'max_leg_length_m', 'max_leg_speed_mps', ...
    'max_leg_acceleration_mps2', 'peak_force_n', 'peak_force_rate_nps', ...
    'control_energy_n2s', 'controller_time_p95_s', 'qp_time_p95_s', ...
    'dob_time_p95_s', 'infeasible_count', 'fallback_count', 'min_sigma', ...
    'min_collision_margin_m', 'min_cbf_residual', 'length_violation_count', ...
    'speed_violation_count', 'acceleration_violation_count', ...
    'force_violation_count', 'force_rate_violation_count', ...
    'collision_violation_count', ...
    'singularity_violation_count', 'nonfinite_count', ...
    'full_trajectory_completed', 'hard_constraints_passed', 'eligible', ...
    'is_training', 'is_holdout'};
summary = array2table(values, 'VariableNames', names);
summary = addvars(summary, controller, caseId, disturbance, scale, seed, stage, ...
    'Before', 1, 'NewVariableNames', {'controller', 'case_id', ...
    'disturbance', 'scale', 'noise_seed', 'validation_stage'});
end
