function feature = grayNarxFeatureVector(pwm, speed, acceleration, grayForce, ...
        previousPwm, previousSpeed, previousGrayForce, previousResidual, previousResidual2)
% grayNarxFeatureVector - 构造包含低速摩擦与换向信息的 NARX 候选回归项
pwm = pwm / 4198;
previousPwm = previousPwm / 4198;
speed = speed / 0.6;
previousSpeed = previousSpeed / 0.6;
acceleration = acceleration / 1.2;
grayForce = grayForce / 2400;
previousGrayForce = previousGrayForce / 2400;
previousResidual = previousResidual / 2400;
previousResidual2 = previousResidual2 / 2400;

feature = [ones(size(pwm)), pwm, speed, acceleration, grayForce, ...
    pwm.^2, speed.^2, pwm .* speed, abs(pwm) .* speed, ...
    sign(speed) .* sqrt(abs(speed)), previousResidual, ...
    sign(speed), sign(pwm), abs(speed), ...
    sign(speed) .* exp(-(abs(speed) / 0.05).^2), ...
    sign(pwm) .* exp(-(abs(speed) / 0.02).^2), ...
    pwm - previousPwm, speed - previousSpeed, previousGrayForce, previousResidual2];
end
