function writeStrictExactModelStudySummary(fileName, result)
% writeStrictExactModelStudySummary - Write an auditable plain-text manifest.
fid = fopen(fileName, 'w');
if fid < 0
    error('writeStrictExactModelStudySummary:OpenFailed', ...
        'Could not open %s for writing.', fileName);
end
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, 'Strict CLF-CBF-QP exact nonlinear model study\n');
fprintf(fid, 'Generated: %s\n', char(result.generatedAt));
fprintf(fid, 'Trajectory: %s\n', result.trajectoryFile);
fprintf(fid, 'Control period: %.12g s\n', result.strictConfig.dt);
fprintf(fid, 'Integration substeps: %d\n', ...
    result.settings.integrationSubsteps);
fprintf(fid, 'Collision HOCBF alpha1/alpha2: %.12g / %.12g\n', ...
    result.strictConfig.cbf.collisionAlpha1, ...
    result.strictConfig.cbf.collisionAlpha2);
fprintf(fid, 'Hard constraints were not relaxed.\n');
fprintf(fid, ['Guarantee scope: only full_qp_nominal is the matched, ' ...
    'ideal-force strict-safety validation.  Disturbed runs are engineering ' ...
    'robustness evidence and carry no unconditional safety guarantee.\n\n']);

for index = 1:numel(result.runs)
    run = result.runs(index);
    m = run.metrics;
    fprintf(fid, '[%s] %s\n', run.scenario.id, run.scenario.displayName);
    fprintf(fid, '  disturbance: %s\n', run.scenario.disturbance);
    fprintf(fid, '  guaranteeApplicable: %d\n', ...
        run.scenario.guaranteeApplicable);
    fprintf(fid, '  translation RMSE/peak [m]: %.12g / %.12g\n', ...
        m.translationRmse, m.translationPeak);
    fprintf(fid, '  rotation RMSE/peak [rad]: %.12g / %.12g\n', ...
        m.rotationRmse, m.rotationPeak);
    fprintf(fid, '  leg length min/max [m]: %.12g / %.12g\n', ...
        m.minLegLength, m.maxLegLength);
    fprintf(fid, '  leg speed/acceleration peak: %.12g / %.12g\n', ...
        m.maxLegSpeed, m.maxLegAcceleration);
    fprintf(fid, '  actual collision distance/margin min [m]: %.12g / %.12g\n', ...
        m.minActualCollisionDistance, m.minActualCollisionMargin);
    fprintf(fid, '  sigma min/lower-bound min: %.12g / %.12g\n', ...
        m.minSigma, m.minSigmaLower);
    fprintf(fid, '  sigma lower-bound maximum excess: %.12g\n', ...
        m.maxSigmaLowerBoundExcess);
    fprintf(fid, '  collision certificate maximum excess [m]: %.12g\n', ...
        m.maxCollisionCertificateExcess);
    fprintf(fid, '  command/applied force peak [N]: %.12g / %.12g\n', ...
        m.peakCommandForce, m.peakAppliedForce);
    fprintf(fid, '  command/applied force-rate peak [N/s]: %.12g / %.12g\n', ...
        m.peakCommandForceRate, m.peakAppliedForceRate);
    fprintf(fid, '  energy [N^2 s]: %.12g\n', m.controlEnergy);
    fprintf(fid, '  CLF slack max/mean: %.12g / %.12g\n', ...
        m.maxClfSlack, m.meanClfSlack);
    fprintf(fid, '  command/realized CBF residual min: %.12g / %.12g\n', ...
        m.minCommandCbfResidual, m.minRealizedCbfResidual);
    fprintf(fid, '  infeasible/fallback: %d / %d\n', ...
        m.infeasibleCount, m.fallbackCount);
    fprintf(fid, '  QP mean/p95/max [ms]: %.12g / %.12g / %.12g\n', ...
        1e3*m.qpTimeMean, 1e3*m.qpTimeP95, 1e3*m.qpTimeMax);
    fprintf(fid, '  engineeringPassed/strictMatchedPassed: %d / %d\n\n', ...
        m.engineeringPassed, m.strictMatchedPassed);
    if m.terminatedEarly
        fprintf(fid, '  TERMINATED EARLY at %.12g s: %s\n\n', ...
            run.termination.time, run.termination.reason);
    end
end
end
