function ad = getStrictClfCbfAdModel(model, scene, config)
% getStrictClfCbfAdModel - Cache the CasADi graph for repeated control steps.
persistent cachedKey cachedModel
key = modelFingerprint(model, scene, config);
if isempty(cachedKey) || ~strcmp(cachedKey, key)
    cachedModel = buildStrictClfCbfAdModel(model, scene, config);
    cachedKey = key;
end
ad = cachedModel;
end

function key = modelFingerprint(model, scene, config)
values = [model.A(:); model.B(:); model.legMap(:); ...
    model.dynamics.totalMass; model.dynamics.comP(:); ...
    model.dynamics.inertiaAtCOM_P(:); double(model.dynamics.includeGravity); ...
    model.g(:); model.singularity.characteristicLength; config.sigmaSafe; ...
    config.collision.smoothingEpsilon; scene.box.R_S(:); ...
    scene.objectCylinder.center_P(:); scene.objectCylinder.axis_P(:); ...
    scene.objectCylinder.length; scene.objectCylinder.radius; ...
    scene.q0(:); scene.qWaypoint(:); scene.qGoal(:); ...
    scene.hood.roof.center_S(:); scene.hood.roof.halfSize(:); ...
    scene.hood.roof.R_S(:); ...
    scene.hood.leftSkirt.center_S(:); scene.hood.leftSkirt.halfSize(:); ...
    scene.hood.leftSkirt.R_S(:); ...
    scene.hood.rightSkirt.center_S(:); scene.hood.rightSkirt.halfSize(:); ...
    scene.hood.rightSkirt.R_S(:)];
key = sprintf('%.17g,', values);
end
