function layout = makeStrictQpSimscapeDiagnosticLayout()
% makeStrictQpSimscapeDiagnosticLayout - Fixed numeric logging contract.
%
% The Level-2 S-function cannot emit variable-size strings.  This layout
% therefore logs every strict-QP margin/residual and a numeric active mask;
% the corresponding names travel with the saved setup structure.

layout = struct();
layout.width = 160;
layout.header = struct( ...
    'clfSlack', 1, ...
    'solveTime', 2, ...
    'feasible', 3, ...
    'usedFallback', 4, ...
    'exitflag', 5, ...
    'minimumCbfResidual', 6, ...
    'hardConstraintViolation', 7, ...
    'clfValue', 8, ...
    'sigmaLowerSquared', 9, ...
    'minimumStateMargin', 10, ...
    'minimumPsi1', 11, ...
    'activeConstraintCount', 12, ...
    'solverError', 13, ...
    'usesFiniteDifferences', 14, ...
    'controllerStepTime', 15, ...
    'simulinkInitializationTime', 16);

layout.stateNames = [interleavedNames("length_lower_", "length_upper_"); ...
    interleavedNames("speed_upper_", "speed_lower_"); ...
    "collision_roof"; "collision_left"; "collision_right"; "singularity"];
layout.psi1Names = [interleavedNames("length_lower_", "length_upper_"); ...
    "collision_roof"; "collision_left"; "collision_right"; "singularity"];
layout.cbfConstraintNames = [ ...
    interleavedNames("length_lower_", "length_upper_"); ...
    interleavedNames("speed_upper_", "speed_lower_"); ...
    interleavedNames("acceleration_upper_", "acceleration_lower_"); ...
    "collision_roof"; "collision_left"; "collision_right"; "singularity"];
layout.forceBoundNames = interleavedNames("force_lower_", "force_upper_");
layout.activeConstraintNames = [layout.cbfConstraintNames; layout.forceBoundNames];

cursor = 17;
layout.stateMargins = cursor:(cursor+numel(layout.stateNames)-1);
cursor = layout.stateMargins(end)+1;
layout.psi1 = cursor:(cursor+numel(layout.psi1Names)-1);
cursor = layout.psi1(end)+1;
layout.cbfResidual = cursor:(cursor+numel(layout.cbfConstraintNames)-1);
cursor = layout.cbfResidual(end)+1;
layout.activeMask = cursor:(cursor+numel(layout.activeConstraintNames)-1);
layout.usedWidth = layout.activeMask(end);
if layout.usedWidth > layout.width
    error('makeStrictQpSimscapeDiagnosticLayout:WidthTooSmall', ...
        'The fixed diagnostic width must be at least %d.', layout.usedWidth);
end
end

function names = interleavedNames(lowerPrefix, upperPrefix)
names = strings(12, 1);
for index = 1:6
    names(2*index-1) = lowerPrefix+index;
    names(2*index) = upperPrefix+index;
end
end
