%% test_14_ihsid_hessian_grid_contract - IHSID Hessian/网格对比入口契约测试
% 只做 dry-run 契约检查，避免单元测试承担完整优化求解时间。

projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(projectRoot, 'opt_minimal'));
addpath(fullfile(projectRoot, 'src'));

assert(exist('run_08_compare_IHSID_hessian_grid', 'file') == 2, ...
    '必须提供单独的 IHSID Hessian/网格对比入口。');

result = run_08_compare_IHSID_hessian_grid( ...
    'gridList', [2 1], ...
    'hessianModes', {'exact', 'limited-memory'}, ...
    'maxIter', 0, ...
    'printLevel', 0, ...
    'dryRun', true);

T = result.summaryTable;
requiredColumns = ["caseName", "method", "N1", "N2", "hessianMode", ...
    "ipoptHessianApproximation", "n_eval_hess_l", "time_hess_l", ...
    "comparisonGroup", "failureReason"];
assert(height(T) == 2, '一个网格和两个 Hessian 模式必须产生两行结果。');
assert(all(string(T.method) == "IHSID"), '该入口必须只维护 IHSID 主线。');
assert(all(string(T.comparisonGroup) == "IHSID-HESSIAN-GRID"), ...
    '必须标记为 IHSID Hessian/网格对比组。');
assert(all(ismember(requiredColumns, string(T.Properties.VariableNames))), ...
    'summaryTable 缺少 Hessian 对比所需字段。');
assert(isequal(sort(string(T.hessianMode)), sort(["exact"; "limited-memory"])), ...
    '必须同时输出 exact 与 limited-memory 两个 Hessian 设置。');
assert(all(string(T.hessianMode) == string(T.ipoptHessianApproximation)), ...
    '表格记录的 Hessian 设置必须与 IPOPT 配置一致。');
assert(isfile(result.csvFile) && isfile(result.reportFile) && isfile(result.readmeFile), ...
    'dry-run 也必须写出 CSV、报告和 README，便于实验前检查。');

disp('test_14_ihsid_hessian_grid_contract passed');
