function estimator = initializePoseImuUkf(config)
% initializePoseImuUkf - 在回零锚点初始化相对编码器与 IMU UKF
initialState = [config.anchorPose; zeros(12, 1)];
stateTransition = @(state, imuInput) propagatePoseImuUkfState(state, imuInput, config);
measurement = @(state) measurePoseImuUkfState(state, config);
filter = unscentedKalmanFilter(stateTransition, measurement, initialState);

dt = config.sampleTime;
translationNoise = config.accelerationNoiseStd;
rotationNoise = config.angularVelocityNoiseStd;
filter.ProcessNoise = diag([ ...
    (0.5 * dt^2 * translationNoise)^2 * ones(3, 1); ...
    (dt * rotationNoise)^2 * ones(3, 1); ...
    (dt * translationNoise)^2 * ones(3, 1); ...
    rotationNoise^2 * ones(3, 1); ...
    (sqrt(dt) * config.accelerometerBiasRandomWalkStd).^2; ...
    (sqrt(dt) * config.gyroBiasRandomWalkStd).^2]);
filter.MeasurementNoise = diag([ ...
    config.encoderNoiseStd^2 * ones(6, 1); ...
    config.orientationNoiseStd.^2]);
filter.StateCovariance = diag([ ...
    config.initialPositionStd^2 * ones(3, 1); ...
    config.initialOrientationStd.^2; ...
    config.initialTranslationVelocityStd^2 * ones(3, 1); ...
    config.initialRotationVelocityStd^2 * ones(3, 1); ...
    config.initialAccelerometerBiasStd.^2; ...
    config.initialGyroBiasStd.^2]);

estimator = struct('filter', filter, 'config', config, 'sampleCount', 0);
end
